# Generated by Django 2.1.7 on 2019-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ojDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OJ', models.CharField(max_length=20, verbose_name='OJ平台')),
                ('Prob', models.CharField(max_length=20, verbose_name='题目ID')),
                ('accept', models.CharField(max_length=5, verbose_name='通过情况')),
                ('oj_user', models.CharField(max_length=100, verbose_name='oj用户名')),
                ('user', models.CharField(max_length=100, verbose_name='用户名')),
            ],
            options={
                'verbose_name': 'OJ记录',
                'verbose_name_plural': 'OJ记录',
            },
        ),
    ]
