# Generated by Django 2.1.7 on 2019-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
