# Generated by Django 2.1.7 on 2019-04-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(blank=True, default='editor', max_length=100, null=True),
        ),
    ]
