# Generated by Django 2.1.7 on 2019-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190408_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vjudge',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
